### ISSUE TITLE
Where does the data of mongodb come from?

### ISSUE THREAD

**Issue by imhuzi** [EOSEssentials/EOSTracker-API#14]
Where does the data of mongodb come from?

**Comment by pojono** [comment]
same question

**Comment by kesar** [comment]
it comes from the mongo_db_plugin of eosio ( https://github.com/EOSIO/eos/tree/master/plugins/mongo_db_plugin ) 

So you would need a eos daemon running with that plugin in order to populate your mongodb 👍
