### ISSUE TITLE
Where do the data for mainnet come from?

### ISSUE THREAD

**Issue by ripley** [EOSEssentials/EOSTracker-API#16]
I tried to parse blocks with Dawn4 testnet, but seems all DB plugins for Dawn4 are broken now, sql_db_plugin and mongo_plugin.

May I ask how to fetch data from mainnet? without that the API is not functional.

**Comment by kesar** [comment]
Hi! Im working also in the sql plugin, almost done

**Comment by ripley** [comment]
OK, awesome work !

**Comment by kesar** [comment]
https://github.com/EOSIO/eos/pull/3882
