### ISSUE TITLE
removed mongo_db_plugin 

### ISSUE THREAD

**Issue by trungtt198x** [EOSEssentials/EOSTracker-API#17]
@kesar 
Please allow me to ask that, the latest commit of the EOS source code on master branch `cbf28a237f3f2605b4ac34c5bb0c98a4d931e99f` has disabled the `mongo_db_plugin`.

So, how can still your EOSTracker tool work?

The `sql_db_plugin` is also disabled by default.

**Comment by kesar** [comment]
![giphy](https://user-images.githubusercontent.com/1288106/40845742-e5ec20c4-65b7-11e8-9f7d-cf8362c20236.gif)


I'm working also in the sql plugin, I am doing latest refactorings + testing to release it 👍

**Comment by trungtt198x** [comment]
@kesar 
Thanks for your respond.
But do you know how to enable the sql plugin or the mongo plugin from the build script of EOS `eosio_build.sh`?

Currently, the nodeos executable is completely disabled with both of the sql- and mongo plugins.
So, we cannot get nodeos connect to sql nor mongo.

**Comment by kesar** [comment]
you can find it here: https://github.com/EOSIO/eos/pull/3882
