### ISSUE TITLE
[QUESTION] How to implement /messages ?

### ISSUE THREAD

**Issue by ripley** [EOSEssentials/EOSTracker-API#18]
Hello Kesar

May I ask how did you implement the /messages API? 

I managed to set up a down 3.0 local testnet and your Tracker-API. I just find /actions interface but no /messages API as in you eostracker.io website.

I didn't find message table in mongo db either.

>  $ show collections
Accounts
ActionTraces
Actions
Blocks
Transactions

Thank you.

**Comment by kesar** [comment]
its actions and using sql plugin you can find it in the eosio repository. 👍
