### ISSUE TITLE
SQL error and nodeos force exit, data need resync

### ISSUE THREAD

**Issue by dbarobin** [EOSEssentials/EOSTracker-API#25]
Some sql error exists in the nodeos log, and the nodeos force quit. Yet I have to delete blocks file of EOS blockchain and eos database in MySQL to force resync, how to avoid and solve this problem?

Thanks.

**Comment by kesar** [comment]
I need the error, otherwise its hard to say. Please try to find in the logs

**Comment by dbarobin** [comment]
@kesar sync to zhengjinhua1, and nodoes exit. The log as follows:

``` bash
terminate called after throwing an instance of 'soci::mysql_soci_error'                                                                            
  what():  Out of range value for column 'amount' at row 1 while executing "INSERT INTO tokens(account, amount, symbol) VALUES (:ac, :am, :as) " with :ac="zhengjinhua1", :am=1e+10, :as="UXB".  
```

**Comment by dbarobin** [comment]
The amount filed of `tokens` table defines **double(14,4)**, but 1e+10 means 10 billion, it exceed the maximum.

**Comment by kesar** [comment]
merged 👍 thx!
