### ISSUE TITLE
how to set password to connect mysql

### ISSUE THREAD

**Issue by wangyilin1987** [EOSEssentials/EOSTracker-API#27]
error:Driver->connect(array('url' => 'mysql://tic@localhost/tic@tic', 'driver' => 'pdo_mysql', 'charset' => 'UTF8', 'host' => 'localhost', 'port' => null, 'user' => 'tic', 'password' => null, 'driverOptions' => array(), 'serverVersion' => 5.7, 'defaultTableOptions' => array(), 'dbname' => 'tic'), 'tic', null, array())

password is null!where set password?

**Comment by newbieh4cker** [comment]
mysql://user:password@host/dbname
ex=>mysql://root:toor@localhost/eos

**Comment by wangyilin1987** [comment]
thank you!!

2018-07-10 



wang_yi_lin 



发件人： newbieh4cker 
发送时间： 2018-07-10  14:45:57 
收件人： EOSEssentials/EOSTracker-API 
抄送： wangyilin1987; Author 
主题： Re: [EOSEssentials/EOSTracker-API] how to set password to connectmysql (#27) 
 
mysql://user:password@host/dbname
ex=>mysql://root:toor@localhost/eos

**Comment by kesar** [comment]
👍 thx @newbieh4cker
