### ISSUE TITLE
How to set the current database

### ISSUE THREAD

**Issue by cppfuns** [EOSEssentials/EOSTracker-API#35]
I edit parameters.yml to see support for 3 kinds of databases,
I want to use the mysql database and get the following data through the installation wizard
parameters:
    secret: ThisTokenIsNotSoSecretChangeIt
    env(DB_URL): 'mysql://root:password@localhost/eos'
    env(MONGO_URL): 'mongodb://localhost:27017/EOS'
    env(REDIS_URL): 'redis://root@localhost:423432'

But always use Redis configuration after running
![image](https://user-images.githubusercontent.com/7980920/43906104-0b154864-9c25-11e8-9bbf-e717335d67a8.png)
How will I set mysql to the current database?

**Comment by cppfuns** [comment]
@kesar

**Comment by kesar** [comment]
Redis is used for cache purposes,  not as database, I think it may be needed unless you know how to change the code to use another cache layer.

Definetly we need to improve the code to not having redis as mandatory

**Comment by cppfuns** [comment]
When I installed and configured Redis, the issue was resolved。
